const PARTNER_STATUS = {
  ACTIVE: 'ACTIVE',
  TERMINATED: 'TERMINATED',
  UNAVAILABLE: 'UNAVAILABLE',
  PENDING: 'PENDING',
  LIMITED_SERVICE: 'LIMITED_SERVICE'
} as const

const PARTNER_PERMISSIONS = {
  READ: 'READ',
  WRITE: 'WRITE',
  BALANCE_INQUIRY: 'BALANCE_INQUIRY'
} as const

export { PARTNER_STATUS, PARTNER_PERMISSIONS }
