const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  REVERSED: 'REVERSED',
  INVALIDATED: 'INVALIDATED'
} as const

const TRANSACTION_TYPE = {
  PAYMENT: 'PAYMENT',
  REFUND: 'REFUND',
  ADJUSTMENT: 'ADJUSTMENT',
  CREDIT: 'CREDIT',
  PENALTY: 'PENALTY',
  INTERNAL: 'INTERNAL'
} as const

export { TRANSACTION_STATUS, TRANSACTION_TYPE }
