name: PayWithPretendPointsAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.7.0'
      - name: Install dependencies
        uses: actions/setup-node@v4
      - run: npm ci
      - name: Check prettier formatting
        uses: actions/setup-node@v4
      - run: npm run action:format
      - name: Check eslint compliance
        uses: actions/setup-node@v4
      - run: npm run action:lint
      - name: Check typescript types
        uses: actions/setup-node@v4
      - run: npm run action:types
      - name: Build Express.js app
        uses: actions/setup-node@v4
      - run: npm run action:build
